# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "373349d948621559bd7e23797dfcaa57"
application_url = "http://127.0.0.1:8000/api/shopify/install"
embedded = false
name = "Qtane - Order Edit"
handle = "opt-order-edit"

[build]
dev_store_url = "shopninja-optimarko.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2024-10"

[auth]
redirect_urls = [ "http://127.0.0.1:8000/api/shopify/grant-code" ]

[pos]
embedded = false
